### ISSUE TITLE
关于数据中词性、句法特征来源

### ISSUE THREAD

**Issue by YuanWind** [CCChenhao997/EMCGCN-ASTE#2]
您好，请问数据中的词性、句法信息是人工标注的还是用工具自动标的呢？如果是工具，方便说一下是哪个工具吗？非常感谢！

**Comment by CCChenhao997** [comment]
All linguistic features of sentences are parsed by [Stanza](https://stanfordnlp.github.io/stanza/).

**Comment by CCChenhao997** [comment]
> 您好，请问数据中的词性、句法信息是人工标注的还是用工具自动标的呢？如果是工具，方便说一下是哪个工具吗？非常感谢！

All linguistic features of sentences are parsed by [Stanza](https://stanfordnlp.github.io/stanza/).

**Comment by YuanWind** [comment]
Thanks
